server:
  port: 8888

spring:
  cloud:
    config:
      enabled: true
      server:
        svn:
          uri: http://123.127.2.213:6248/repos/bdap/应用支持/spring/repo/
          username: yang.bin
          password: fcv6rs
        default-label: trunk
  profiles:
    active: subversion